

## Omnomnomics pipeline config ##
##Master config
#set step indices
trim_rule_num: 1 
qc_rule_num: 2
map_rule_num: 3
merge_rule_num: 4
touchup_rule_num: 5
index_rule_num: 6
stats_rule_num: 7
tagdir_rule_num: 8
wig_rule_num: 9
mergewig_rule_num: 10
callpeaks_rule_num: 11
countreads_rule_num: 12
de_rule_num: 13

#Define the maximum number of steps as the biggest step index given above
max_step: 13


trim:
  - "run_skewer"
  - "run_trimmomatic"
qc:
  - "run_fastqc"
map:
  - "run_hisat2"
  - "run_star"
  - "run_star_te"
merge:
  - "merge_bam"
touchup:
  - "touchup_bam"
index:
  - "index_bam"
stats:
  - "bam_stats"
tagdir:
  - "create_homer_tagDir"
wig:
  - "create_wiggles"
mergewig:
  - "merge_wiggles"
callpeaks:
  - "call_peaks"
countreads:
  - "count_reads"
de:
  - "call_DE"


selected_routine_trim: 0
selected_routine_qc: 0
selected_routine_map: 0
selected_routine_merge: 0
selected_routine_touchup: 0
selected_routine_index: 0
selected_routine_stats: 0
selected_routine_tagdir: 0
selected_routine_wig: 0
selected_routine_mergewig: 0
selected_routine_callpeaks: 0
selected_routine_countreads: 0
selected_routine_de: 0

routines:
  - trim
  - qc
  - map
  - merge
  - touchup
  - index
  - stats
  - tagdir
  - wig
  - mergewig
  - callpeaks
  - countreads
  - de



input_folders:
  - "FASTQ"
  - "trimmed_FASTQ"
  - "trimmed_FASTQ"
  - "BAM"
  - "BAM"
  - "filtered_BAM"
  - "filtered_BAM"
  - "filtered_BAM"
  - "HOMER_tagDirs"
  - "BigWigs"
  - ["filtered_BAM", "HOMER_tagDirs"]
  - ["HOMER_tagDirs", "peak_calling"]
  - "DE_calling"

output_folders:
  - "trimmed_FASTQ"
  - "fastqc_reports"
  - "BAM"
  - "BAM"
  - "filtered_BAM"
  - "filtered_BAM"
  - "filtered_BAM"
  - "HOMER_tagDirs"
  - "BigWigs"
  - "merged_hubs"
  - "peak_calling"
  - "DE_calling"
  - "DE_calling"

input_file_types: ####update this by looking at rules
  - ".fastq.gz"
  - ".trimmed.fastq.gz"
  - ".trimmed.fastq.gz"
  - ".bam"
  - ".bam"
  - ".filtered.bam"
  - ".filtered.bam"
  - ".filtered.bam"
  - ".HOMER_tagDir.tar.gz"
  - [".hub", ".bw"]
  - [".bam", ".HOMER_tagDir.tar.gz"]
  - [".HOMER_tagDir.tar.gz", ".bed"]
  - ".raw_read_quant.table.txt"

### added output file types
output_file_types: 
  - ".trimmed.fastq.gz"
  - [".trimmed_fastqc.html", ".trimmed_fastqc.zip"]
  - ".bam"
  - ".bam"
  - ".sorted.dups_marked.filtered.bam"
  - ".sorted.dups_marked.filtered.bam.bai"
  - ".sorted.dups_marked.filtered.bam.stats.txt"
  - ".HOMER_tagDir.tar.gz"
  - [".bw", ".hub"]
  - ".hub"
  - ".bed"
  - ".raw_read_quant.table.txt"
  - ".results.zip"

mincores_single_sample_step1_9:
  - 8
  - 1
  - 8
  - 1
  - 5
  - 1
  - 1
  - 1
  - 1

maxcores_single_sample_step1_9:
  - 128 
  - 128 
  - 128 
  - 128 
  - 128 
  - 1
  - 1
  - 1
  - 1

mincores_per_rule_run_step10_13:
  - 1
  - 1
  - 1
  - 1

maxcores_per_rule_run_step10_13:
  - 1
  - 128
  - 1
  - 1

min_mem_mb:
  - 32000 
  -  
  - 32000
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  -
  -
  - 
  



MAPPERS: ["hisat2", "star", "star_te"]
TRIMMERS: ["skewer", "trimmomatic"]
TYPES: ["RNA", "CHIP", "ATAC"]
GENOMES: ["hg38", "mm10", "mm39", "GRCh38.p14", "GRCm39"]

partition: "defq"
max_nodes: 10


#slurm config, get from sinfo or obligate to fill out
nodes_in_partition: 10 
cores_per_node: 128
max_mem_per_core_mb: 4000
min_slice_cores: 1
min_slice_mem: 4000


omnom_home: "/net/beegfs/scratch/kcarroll/Amsterdam_UMC_Klinische_Genetica_Internship"
trim_tool: "skewer"
map_tool: "hisat2"
omnomnomics: 0.4
mode: "auto"
formula: "1"
broad: "NA"
input: "NA"
homer_input: "NA"
the_style: "factor"
homer_size: 500
homer_mindist: 2000
metadata: "NA"
name_fields: "1,8,11"
type_field: "1"
col_field: "2"
separator: "_"
appendix: "hub"
overlay: "transparentOverlay"
color_data_folder: "{OMNOM_HOME}/bin/color_data_for_hubs"
color_table: "{OMNOM_HOME}/bin/color_data_for_hubs/gray.tint.color.table"
hub_mail: "m.dewinther@amsterdamumc.nl"
no_multiqc: False
keep_unpaired: False


homerposcol: "255,150,150"
homernegcol: "255,180,180"
altposcol: "255,128,0"
altnegcol: "0,128,255"

#overlay type command line options
overlaytypes: ["transparentOverlay", "stacked", "solidOverlay", "none"]