cluster:
  mkdir -p slurm_logs/{rule} &&
  worker_constraint="{resources.worker_constraint}" &&
  constraint_args=() &&
  if [ -n "$worker_constraint" ] && [ "$worker_constraint" != "NA" ] && [ "$worker_constraint" != "None" ]; then
    constraint_args=(--constraint="$worker_constraint");
  fi &&
  sbatch
    --partition={resources.partition}
    --export=ALL
    --time={resources.runtime}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    "${constraint_args[@]}"
    --output=slurm_logs/{rule}/{rule}.%j.out
