

## Omnomnomics pipeline config ##
## Site defaults config ##
partition: "rome"
max_nodes: 504

# Snellius Rome thin-node defaults
nodes_in_partition: 504
cores_per_node: 128
max_mem_per_core_mb: 1792
min_slice_cores: 16
min_slice_mem: 32768
default_runtime: "02:00:00"

# External genome resources
genome_assembly_dir: "{HOME}/genomes/assemblies"
cellranger_reference_dir: "{HOME}/genomes/cellranger"
