BROAD: NA
EXPERIMENT_DIR: /net/beegfs/scratch/kcarroll/Amsterdam UMC Klinische Genetica Internship/omnomnomics
HOMERINPUT: NA.HOMER_tagDir
HOMERMINDIST: 2000
HOMERSIZE: 500
INPUT: NA
INPUT_FILE_TYPE: .trimmed.fastq.gz
INPUT_FOLDER: trimmed_FASTQ
KEEPUNPAIRED: 0
MAXCORES: 127
MYFORMULA: '1'
MYMETADATA: NA
NAMEFIELDS: 1-3
NO_MULTIQC: 0
NUMFILES: 2
NUMPAIRS: 1
OMNOM_HOME: /net/beegfs/scratch/kcarroll/Amsterdam UMC Klinische Genetica Internship/omnomnomics
PAIRED: true
RUNDATE: '2024-06-06'
SELECTED_ROUTINE_CALLPEAKS: 0
SELECTED_ROUTINE_COUNTREADS: 0
SELECTED_ROUTINE_DE: 0
SELECTED_ROUTINE_INDEX: 0
SELECTED_ROUTINE_MAP: 0
SELECTED_ROUTINE_MERGE: 0
SELECTED_ROUTINE_MERGEWIG: 0
SELECTED_ROUTINE_QC: 0
SELECTED_ROUTINE_STATS: 0
SELECTED_ROUTINE_TAGDIR: 0
SELECTED_ROUTINE_TOUCHUP: 0
SELECTED_ROUTINE_TRIM: 0
SELECTED_ROUTINE_WIG: 0
THEAPPENDIX: hub
THECOLFIELD: '2'
THECOLORDATAFOLDER: ${OMNOM_HOME}/bin/color_data_for_hubs
THECOLTABLE: ${OMNOM_HOME}/bin/color_data_for_hubs/gray.tint.color.table
THEGENOME: hg38
THEHEAPINIT: 250000M
THEHUBMAIL: m.dewinther@amsterdamumc.nl
THEMAPTOOL: hisat2
THEMEM: 500000M
THEMODE:
- 3
THEMODERANGEMAX: 3
THEMODERANGEMIN: 3
THEOVERLAY: transparentOverlay
THESEPARATOR: _
THESTYLE: factor
THETRIMTOOL: skewer
THETYPE: RNA
THETYPEFIELD: '1'
